apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ty9v8prdt-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ty9v8prdt-dotnet-basic-gitops